// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/configurator.proto

package sqlaccounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	AppName  string `protobuf:"bytes,4,opt,name=appName,proto3" json:"appName,omitempty"`
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type IsDcfParsableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DcfPath string `protobuf:"bytes,1,opt,name=dcfPath,proto3" json:"dcfPath,omitempty"`
}

func (x *IsDcfParsableRequest) Reset() {
	*x = IsDcfParsableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsDcfParsableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDcfParsableRequest) ProtoMessage() {}

func (x *IsDcfParsableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDcfParsableRequest.ProtoReflect.Descriptor instead.
func (*IsDcfParsableRequest) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{1}
}

func (x *IsDcfParsableRequest) GetDcfPath() string {
	if x != nil {
		return x.DcfPath
	}
	return ""
}

type Database struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database    string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	CompanyName string `protobuf:"bytes,2,opt,name=companyName,proto3" json:"companyName,omitempty"`
	Remark      string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Version     string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	DbUsername  string `protobuf:"bytes,5,opt,name=dbUsername,proto3" json:"dbUsername,omitempty"`
	DbPassword  string `protobuf:"bytes,6,opt,name=dbPassword,proto3" json:"dbPassword,omitempty"`
}

func (x *Database) Reset() {
	*x = Database{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{2}
}

func (x *Database) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Database) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Database) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Database) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Database) GetDbUsername() string {
	if x != nil {
		return x.DbUsername
	}
	return ""
}

func (x *Database) GetDbPassword() string {
	if x != nil {
		return x.DbPassword
	}
	return ""
}

type IsDcfParsableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database []*Database `protobuf:"bytes,1,rep,name=database,proto3" json:"database,omitempty"`
}

func (x *IsDcfParsableResponse) Reset() {
	*x = IsDcfParsableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsDcfParsableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDcfParsableResponse) ProtoMessage() {}

func (x *IsDcfParsableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDcfParsableResponse.ProtoReflect.Descriptor instead.
func (*IsDcfParsableResponse) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{3}
}

func (x *IsDcfParsableResponse) GetDatabase() []*Database {
	if x != nil {
		return x.Database
	}
	return nil
}

type TempPathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TempPath string `protobuf:"bytes,1,opt,name=tempPath,proto3" json:"tempPath,omitempty"`
}

func (x *TempPathRequest) Reset() {
	*x = TempPathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TempPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempPathRequest) ProtoMessage() {}

func (x *TempPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempPathRequest.ProtoReflect.Descriptor instead.
func (*TempPathRequest) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{4}
}

func (x *TempPathRequest) GetTempPath() string {
	if x != nil {
		return x.TempPath
	}
	return ""
}

type PatchUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatchUrl string `protobuf:"bytes,1,opt,name=patchUrl,proto3" json:"patchUrl,omitempty"`
}

func (x *PatchUrlRequest) Reset() {
	*x = PatchUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchUrlRequest) ProtoMessage() {}

func (x *PatchUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchUrlRequest.ProtoReflect.Descriptor instead.
func (*PatchUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{5}
}

func (x *PatchUrlRequest) GetPatchUrl() string {
	if x != nil {
		return x.PatchUrl
	}
	return ""
}

type HookUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HookUrl string `protobuf:"bytes,1,opt,name=hookUrl,proto3" json:"hookUrl,omitempty"`
}

func (x *HookUrlRequest) Reset() {
	*x = HookUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HookUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookUrlRequest) ProtoMessage() {}

func (x *HookUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookUrlRequest.ProtoReflect.Descriptor instead.
func (*HookUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{6}
}

func (x *HookUrlRequest) GetHookUrl() string {
	if x != nil {
		return x.HookUrl
	}
	return ""
}

type ReachableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ReachableRequest) Reset() {
	*x = ReachableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReachableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReachableRequest) ProtoMessage() {}

func (x *ReachableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReachableRequest.ProtoReflect.Descriptor instead.
func (*ReachableRequest) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{7}
}

func (x *ReachableRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LoginConfiguratorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginConfiguratorRequest) Reset() {
	*x = LoginConfiguratorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginConfiguratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginConfiguratorRequest) ProtoMessage() {}

func (x *LoginConfiguratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginConfiguratorRequest.ProtoReflect.Descriptor instead.
func (*LoginConfiguratorRequest) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{8}
}

func (x *LoginConfiguratorRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginConfiguratorRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PluginResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PluginResult) Reset() {
	*x = PluginResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginResult) ProtoMessage() {}

func (x *PluginResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginResult.ProtoReflect.Descriptor instead.
func (*PluginResult) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{9}
}

func (x *PluginResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PluginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []*PluginResult `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
}

func (x *PluginResponse) Reset() {
	*x = PluginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginResponse) ProtoMessage() {}

func (x *PluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginResponse.ProtoReflect.Descriptor instead.
func (*PluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{10}
}

func (x *PluginResponse) GetRes() []*PluginResult {
	if x != nil {
		return x.Res
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configurator_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configurator_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_configurator_proto_rawDescGZIP(), []int{11}
}

var File_proto_configurator_proto protoreflect.FileDescriptor

var file_proto_configurator_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x71, 0x6c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x73, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x30,
	0x0a, 0x14, 0x49, 0x73, 0x44, 0x63, 0x66, 0x50, 0x61, 0x72, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x63, 0x66, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x63, 0x66, 0x50, 0x61, 0x74, 0x68,
	0x22, 0xba, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x62, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x62, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x62, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x62, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x4c, 0x0a,
	0x15, 0x49, 0x73, 0x44, 0x63, 0x66, 0x50, 0x61, 0x72, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x0f, 0x54,
	0x65, 0x6d, 0x70, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x50, 0x61, 0x74, 0x68, 0x22, 0x2d, 0x0a, 0x0f, 0x50, 0x61,
	0x74, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x74, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x74, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x22, 0x2a, 0x0a, 0x0e, 0x48, 0x6f, 0x6f,
	0x6b, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68,
	0x6f, 0x6f, 0x6b, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f,
	0x6f, 0x6b, 0x55, 0x72, 0x6c, 0x22, 0x24, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x52, 0x0a, 0x18, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x38, 0x0a, 0x0c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3f, 0x0a, 0x0e, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x03, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x32, 0xe2, 0x05, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x3c, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x5a, 0x0a, 0x0d, 0x49, 0x73, 0x44, 0x63, 0x66,
	0x50, 0x61, 0x72, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x23, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x73, 0x44, 0x63, 0x66, 0x50, 0x61,
	0x72, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x73,
	0x44, 0x63, 0x66, 0x50, 0x61, 0x72, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x73, 0x71,
	0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x43, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x1e, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x54, 0x65, 0x6d, 0x70, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x43, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x50, 0x61, 0x74,
	0x63, 0x68, 0x55, 0x72, 0x6c, 0x12, 0x1e, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x0a, 0x53,
	0x65, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x2e, 0x73, 0x71, 0x6c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x44,
	0x0a, 0x0b, 0x49, 0x73, 0x52, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1f, 0x2e,
	0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65,
	0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x52, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x27, 0x2e, 0x73, 0x71, 0x6c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x45, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x14, 0x2e, 0x73, 0x71, 0x6c,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1d, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x10, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x12, 0x14, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x73, 0x71, 0x6c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x61, 0x73, 0x79, 0x74, 0x65, 0x63, 0x68, 0x2d,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x73, 0x64,
	0x6e, 0x2d, 0x62, 0x68, 0x64, 0x2f, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_configurator_proto_rawDescOnce sync.Once
	file_proto_configurator_proto_rawDescData = file_proto_configurator_proto_rawDesc
)

func file_proto_configurator_proto_rawDescGZIP() []byte {
	file_proto_configurator_proto_rawDescOnce.Do(func() {
		file_proto_configurator_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_configurator_proto_rawDescData)
	})
	return file_proto_configurator_proto_rawDescData
}

var file_proto_configurator_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_configurator_proto_goTypes = []any{
	(*CreateRequest)(nil),            // 0: sqlaccounting.CreateRequest
	(*IsDcfParsableRequest)(nil),     // 1: sqlaccounting.IsDcfParsableRequest
	(*Database)(nil),                 // 2: sqlaccounting.Database
	(*IsDcfParsableResponse)(nil),    // 3: sqlaccounting.IsDcfParsableResponse
	(*TempPathRequest)(nil),          // 4: sqlaccounting.TempPathRequest
	(*PatchUrlRequest)(nil),          // 5: sqlaccounting.PatchUrlRequest
	(*HookUrlRequest)(nil),           // 6: sqlaccounting.HookUrlRequest
	(*ReachableRequest)(nil),         // 7: sqlaccounting.ReachableRequest
	(*LoginConfiguratorRequest)(nil), // 8: sqlaccounting.LoginConfiguratorRequest
	(*PluginResult)(nil),             // 9: sqlaccounting.PluginResult
	(*PluginResponse)(nil),           // 10: sqlaccounting.PluginResponse
	(*Empty)(nil),                    // 11: sqlaccounting.Empty
}
var file_proto_configurator_proto_depIdxs = []int32{
	2,  // 0: sqlaccounting.IsDcfParsableResponse.database:type_name -> sqlaccounting.Database
	9,  // 1: sqlaccounting.PluginResponse.res:type_name -> sqlaccounting.PluginResult
	0,  // 2: sqlaccounting.SetupConfigurator.Create:input_type -> sqlaccounting.CreateRequest
	1,  // 3: sqlaccounting.SetupConfigurator.IsDcfParsable:input_type -> sqlaccounting.IsDcfParsableRequest
	2,  // 4: sqlaccounting.SetupConfigurator.SetDatabase:input_type -> sqlaccounting.Database
	4,  // 5: sqlaccounting.SetupConfigurator.SetTempPath:input_type -> sqlaccounting.TempPathRequest
	5,  // 6: sqlaccounting.SetupConfigurator.SetPatchUrl:input_type -> sqlaccounting.PatchUrlRequest
	6,  // 7: sqlaccounting.SetupConfigurator.SetHookUrl:input_type -> sqlaccounting.HookUrlRequest
	7,  // 8: sqlaccounting.SetupConfigurator.IsReachable:input_type -> sqlaccounting.ReachableRequest
	8,  // 9: sqlaccounting.SetupConfigurator.LoginConfigurator:input_type -> sqlaccounting.LoginConfiguratorRequest
	11, // 10: sqlaccounting.SetupConfigurator.InstallPlugins:input_type -> sqlaccounting.Empty
	11, // 11: sqlaccounting.SetupConfigurator.UninstallPlugins:input_type -> sqlaccounting.Empty
	11, // 12: sqlaccounting.SetupConfigurator.Create:output_type -> sqlaccounting.Empty
	3,  // 13: sqlaccounting.SetupConfigurator.IsDcfParsable:output_type -> sqlaccounting.IsDcfParsableResponse
	11, // 14: sqlaccounting.SetupConfigurator.SetDatabase:output_type -> sqlaccounting.Empty
	11, // 15: sqlaccounting.SetupConfigurator.SetTempPath:output_type -> sqlaccounting.Empty
	11, // 16: sqlaccounting.SetupConfigurator.SetPatchUrl:output_type -> sqlaccounting.Empty
	11, // 17: sqlaccounting.SetupConfigurator.SetHookUrl:output_type -> sqlaccounting.Empty
	11, // 18: sqlaccounting.SetupConfigurator.IsReachable:output_type -> sqlaccounting.Empty
	11, // 19: sqlaccounting.SetupConfigurator.LoginConfigurator:output_type -> sqlaccounting.Empty
	10, // 20: sqlaccounting.SetupConfigurator.InstallPlugins:output_type -> sqlaccounting.PluginResponse
	10, // 21: sqlaccounting.SetupConfigurator.UninstallPlugins:output_type -> sqlaccounting.PluginResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_configurator_proto_init() }
func file_proto_configurator_proto_init() {
	if File_proto_configurator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_configurator_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IsDcfParsableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Database); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IsDcfParsableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TempPathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PatchUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*HookUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ReachableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LoginConfiguratorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*PluginResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*PluginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configurator_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_configurator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_configurator_proto_goTypes,
		DependencyIndexes: file_proto_configurator_proto_depIdxs,
		MessageInfos:      file_proto_configurator_proto_msgTypes,
	}.Build()
	File_proto_configurator_proto = out.File
	file_proto_configurator_proto_rawDesc = nil
	file_proto_configurator_proto_goTypes = nil
	file_proto_configurator_proto_depIdxs = nil
}
