// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/manager.proto

package sqlaccounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db       int32  `protobuf:"varint,1,opt,name=db,proto3" json:"db,omitempty"`
	Addr     string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *TaskClientRequest) Reset() {
	*x = TaskClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskClientRequest) ProtoMessage() {}

func (x *TaskClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskClientRequest.ProtoReflect.Descriptor instead.
func (*TaskClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{0}
}

func (x *TaskClientRequest) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *TaskClientRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *TaskClientRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TaskClientRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ApiClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	AppName  string `protobuf:"bytes,4,opt,name=appName,proto3" json:"appName,omitempty"`
}

func (x *ApiClientRequest) Reset() {
	*x = ApiClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiClientRequest) ProtoMessage() {}

func (x *ApiClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiClientRequest.ProtoReflect.Descriptor instead.
func (*ApiClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ApiClientRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ApiClientRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ApiClientRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ApiClientRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type GcpCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonData string `protobuf:"bytes,1,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
}

func (x *GcpCredentialsRequest) Reset() {
	*x = GcpCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GcpCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpCredentialsRequest) ProtoMessage() {}

func (x *GcpCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GcpCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{2}
}

func (x *GcpCredentialsRequest) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type GcpProjectIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
}

func (x *GcpProjectIdRequest) Reset() {
	*x = GcpProjectIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GcpProjectIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpProjectIdRequest) ProtoMessage() {}

func (x *GcpProjectIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpProjectIdRequest.ProtoReflect.Descriptor instead.
func (*GcpProjectIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GcpProjectIdRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type None struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *None) Reset() {
	*x = None{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *None) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*None) ProtoMessage() {}

func (x *None) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use None.ProtoReflect.Descriptor instead.
func (*None) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{4}
}

var File_proto_manager_proto protoreflect.FileDescriptor

var file_proto_manager_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x69, 0x6e, 0x67, 0x22, 0x6f, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x64, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x76, 0x0a, 0x10, 0x41, 0x70, 0x69, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a,
	0x15, 0x47, 0x63, 0x70, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x33, 0x0a, 0x13, 0x47, 0x63, 0x70, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x32,
	0xfd, 0x02, 0x0a, 0x0d, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x12, 0x4c, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x71, 0x6c,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x12,
	0x4a, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x41, 0x70, 0x69, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x70, 0x69, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x12, 0x4e, 0x0a, 0x11, 0x53,
	0x65, 0x74, 0x47, 0x70, 0x63, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x12, 0x24, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x47, 0x63, 0x70, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x53,
	0x65, 0x74, 0x47, 0x63, 0x70, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x22,
	0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x47,
	0x63, 0x70, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x73, 0x71, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x13, 0x2e, 0x73, 0x71, 0x6c,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x61,
	0x73, 0x79, 0x74, 0x65, 0x63, 0x68, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x73, 0x64, 0x6e, 0x2d, 0x62, 0x68, 0x64, 0x2f, 0x73, 0x71, 0x6c,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_manager_proto_rawDescOnce sync.Once
	file_proto_manager_proto_rawDescData = file_proto_manager_proto_rawDesc
)

func file_proto_manager_proto_rawDescGZIP() []byte {
	file_proto_manager_proto_rawDescOnce.Do(func() {
		file_proto_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_manager_proto_rawDescData)
	})
	return file_proto_manager_proto_rawDescData
}

var file_proto_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_manager_proto_goTypes = []any{
	(*TaskClientRequest)(nil),     // 0: sqlaccounting.TaskClientRequest
	(*ApiClientRequest)(nil),      // 1: sqlaccounting.ApiClientRequest
	(*GcpCredentialsRequest)(nil), // 2: sqlaccounting.GcpCredentialsRequest
	(*GcpProjectIdRequest)(nil),   // 3: sqlaccounting.GcpProjectIdRequest
	(*None)(nil),                  // 4: sqlaccounting.None
}
var file_proto_manager_proto_depIdxs = []int32{
	0, // 0: sqlaccounting.ManagerWorker.SetTaskClientConfig:input_type -> sqlaccounting.TaskClientRequest
	1, // 1: sqlaccounting.ManagerWorker.SetApiClientConfig:input_type -> sqlaccounting.ApiClientRequest
	2, // 2: sqlaccounting.ManagerWorker.SetGpcCredentials:input_type -> sqlaccounting.GcpCredentialsRequest
	3, // 3: sqlaccounting.ManagerWorker.SetGcpProjectId:input_type -> sqlaccounting.GcpProjectIdRequest
	4, // 4: sqlaccounting.ManagerWorker.RunManager:input_type -> sqlaccounting.None
	4, // 5: sqlaccounting.ManagerWorker.SetTaskClientConfig:output_type -> sqlaccounting.None
	4, // 6: sqlaccounting.ManagerWorker.SetApiClientConfig:output_type -> sqlaccounting.None
	4, // 7: sqlaccounting.ManagerWorker.SetGpcCredentials:output_type -> sqlaccounting.None
	4, // 8: sqlaccounting.ManagerWorker.SetGcpProjectId:output_type -> sqlaccounting.None
	4, // 9: sqlaccounting.ManagerWorker.RunManager:output_type -> sqlaccounting.None
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_manager_proto_init() }
func file_proto_manager_proto_init() {
	if File_proto_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_manager_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TaskClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_manager_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ApiClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_manager_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GcpCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_manager_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GcpProjectIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_manager_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*None); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manager_proto_goTypes,
		DependencyIndexes: file_proto_manager_proto_depIdxs,
		MessageInfos:      file_proto_manager_proto_msgTypes,
	}.Build()
	File_proto_manager_proto = out.File
	file_proto_manager_proto_rawDesc = nil
	file_proto_manager_proto_goTypes = nil
	file_proto_manager_proto_depIdxs = nil
}
