/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: controls.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.proto = require('./controls_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.ControlManagementClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.ControlManagementPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.Nothing,
 *   !proto.proto.Result>}
 */
const methodDescriptor_ControlManagement_Ping = new grpc.web.MethodDescriptor(
  '/proto.ControlManagement/Ping',
  grpc.web.MethodType.UNARY,
  proto.proto.Nothing,
  proto.proto.Result,
  /**
   * @param {!proto.proto.Nothing} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.Result.deserializeBinary
);


/**
 * @param {!proto.proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.Result)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.Result>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ControlManagementClient.prototype.ping =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/proto.ControlManagement/Ping',
      request,
      metadata || {},
      methodDescriptor_ControlManagement_Ping,
      callback);
};


/**
 * @param {!proto.proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.Result>}
 *     Promise that resolves to the response
 */
proto.proto.ControlManagementPromiseClient.prototype.ping =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/proto.ControlManagement/Ping',
      request,
      metadata || {},
      methodDescriptor_ControlManagement_Ping);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.Nothing,
 *   !proto.proto.Result>}
 */
const methodDescriptor_ControlManagement_Start = new grpc.web.MethodDescriptor(
  '/proto.ControlManagement/Start',
  grpc.web.MethodType.UNARY,
  proto.proto.Nothing,
  proto.proto.Result,
  /**
   * @param {!proto.proto.Nothing} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.Result.deserializeBinary
);


/**
 * @param {!proto.proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.Result)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.Result>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ControlManagementClient.prototype.start =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/proto.ControlManagement/Start',
      request,
      metadata || {},
      methodDescriptor_ControlManagement_Start,
      callback);
};


/**
 * @param {!proto.proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.Result>}
 *     Promise that resolves to the response
 */
proto.proto.ControlManagementPromiseClient.prototype.start =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/proto.ControlManagement/Start',
      request,
      metadata || {},
      methodDescriptor_ControlManagement_Start);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.Nothing,
 *   !proto.proto.Result>}
 */
const methodDescriptor_ControlManagement_Stop = new grpc.web.MethodDescriptor(
  '/proto.ControlManagement/Stop',
  grpc.web.MethodType.UNARY,
  proto.proto.Nothing,
  proto.proto.Result,
  /**
   * @param {!proto.proto.Nothing} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.Result.deserializeBinary
);


/**
 * @param {!proto.proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.Result)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.Result>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ControlManagementClient.prototype.stop =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/proto.ControlManagement/Stop',
      request,
      metadata || {},
      methodDescriptor_ControlManagement_Stop,
      callback);
};


/**
 * @param {!proto.proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.Result>}
 *     Promise that resolves to the response
 */
proto.proto.ControlManagementPromiseClient.prototype.stop =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/proto.ControlManagement/Stop',
      request,
      metadata || {},
      methodDescriptor_ControlManagement_Stop);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.Nothing,
 *   !proto.proto.Result>}
 */
const methodDescriptor_ControlManagement_Restart = new grpc.web.MethodDescriptor(
  '/proto.ControlManagement/Restart',
  grpc.web.MethodType.UNARY,
  proto.proto.Nothing,
  proto.proto.Result,
  /**
   * @param {!proto.proto.Nothing} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.Result.deserializeBinary
);


/**
 * @param {!proto.proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.Result)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.Result>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ControlManagementClient.prototype.restart =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/proto.ControlManagement/Restart',
      request,
      metadata || {},
      methodDescriptor_ControlManagement_Restart,
      callback);
};


/**
 * @param {!proto.proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.Result>}
 *     Promise that resolves to the response
 */
proto.proto.ControlManagementPromiseClient.prototype.restart =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/proto.ControlManagement/Restart',
      request,
      metadata || {},
      methodDescriptor_ControlManagement_Restart);
};


module.exports = proto.proto;

